
name: Install latest dependencies
jobs:
  docs:
    name: Install deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - name: Install newest discord.js version
        run: pnpm i discord.js@dev
 
      - name: Install all other required deps
        run: 'pnpm i $(node -e "for (const K of Object.keys(require(\'./package.json\').dependencies).map(v => v != \'discord.js\')) process.stdout.write(K + " ")")' 
